### ISSUE TITLE
Mock out remote url calls in data lib tests

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#112]
Main reason is that it is a PITA when i'm offline and testing.

However, happy to leave if we think there is a strong reason to keep vs mocking ...

@anuveyatsu your thoughts

## Tasks

* add mocks for all remote url tests in data.js

**Comment by anuveyatsu** [comment]
@rufuspollock not crucial, but nice to have especially when travelling so we can work in a plane/train etc + tests are quicker

**Comment by Mikanebu** [comment]
this issue should go into `data.js` repo

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datahq/data.js/pull/8
