### ISSUE TITLE
[login] Can choose login method

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#117]
We only offer google login on CLI when in fact may be multiple (leading to inconsistency for the user)

## Acceptance criteria

* [x] I can choose login method when I do `data login`

## Tasks

* [x] Offer choice based on what was returned by auth/check

Bonus:

* If expiring token and you have logged in before then use that previous info to default the login method to the one you used previously (so no choice) (?)

**Comment by anuveyatsu** [comment]
FIXED. When a user logs in it will prompt with login options available (it uses what's returned from auth service). See screenshot below:

<img width="245" alt="screen shot 2017-07-26 at 17 07 05" src="https://user-images.githubusercontent.com/17809581/28618578-b5c69b52-7226-11e7-9c72-4bc9684ca1aa.png">
