### ISSUE TITLE
Inversion of control for (tabular) data parsers

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#126]
We want to to be able to easily add new parsers for tabular data (and later other types) e.g. excel #102. We also want the CSV parser to support csv dialect and various options. 

Parsers are a method that takes a resource object and return an object stream: (not sure await is needed?)

```
const objectStream = await parse(resource)
```

## Tasks

* [x]  Refactor current code to this model (including csv)
* [x] Document in README how to add a new parser and the approach (briefly)

## Analysis

Current code for `rows`

```javascript=
_rows() {
  return (async () => {
    if (Object.keys(parserDatabase).indexOf(this.descriptor.format) !== -1) {
      const parser = parserDatabase[this.descriptor.format](this.descriptor)
      const stream = await this.stream
      return stream.pipe(parser)
    }
    throw new Error(`We do not have a parser for that format: ${this.descriptor.format}`)
  })()
}
```

What's not so great about this ...

* Mix of inversion of control
* No inversion of control so e.g. adding a xls option is painful as it does not use stream but buffer

New approach

```
if (this.descriptor.format in parserDatabase) {
  const parser = parserDatabase[format]
  return parser.process(this)
} else {

}
```

Each parser should get a separate file

```
/data.js
/parser/xls.js
/parser/csv.js
```

Later we maybe can even have the parsers register themselves ... e.g. in csv.js

```
export const process(resource) {

}

data.parserDatabase['csv'] = this module ...
```

**Comment by anuveyatsu** [comment]
FIXED. Refactored logic of `_rows()` method so now it only passes `this` to a parser. Updated README with `How to add a new parser` section.
