### ISSUE TITLE
data login does not work properly

### ISSUE THREAD

**Issue by Mikanebu** [datopian/data-cli#127]
Tried to login with DataHub CLI using `data login`.  Browser was opened and redirected to url with jwt, but cli process did not stop and it did not save `~/.datahub.json` file.

**Comment by zelima** [comment]
Another problem: 

* Was logged in and authenticated (was able to push files)
* Tried to push after ~ 15 hours: 
  * `data push` results:
  ```
  > Error! Authz server: INTERNAL SERVER ERROR
  ```
  * `data login` resutls: 
  ```
  > Error! invalid json response body at http://api-testing.datahub.io/auth/check?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyaWQiOiIwZTliNTljZDUwZjE4ODQwNThjMWFhMjQyZDcxYTIyOCIsImV4cCI6MTUwMjEwODc1MX0.cxe2kDMdEW3IMak8Lcfa3rLtDuGFaHidIfRcxaAmPSU&next=http://localhost:3000 reason: Unexpected token < in JSON at position 0

  ```

**Comment by zelima** [comment]
@anuveyatsu I believe this is FIXED now
