### ISSUE TITLE
Error coming up from push command

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#133]
When I've tried to login with `next` endpoint and then pushed to `testing` I got the following error:

```
> Error! request to https://s3.amazonaws.com/rawstore-testing.datahub.io failed, reason: socket hang up
```

But then I run it 2nd time and it went OK.

**Comment by anuveyatsu** [comment]
@Mikanebu can you analyse that issue - try to do pushing with various scenarios. We need to make sure there are no errors.

**Comment by Mikanebu** [comment]
@anuveyatsu ok

**Comment by rufuspollock** [comment]
I'm moving to icebox for this sprint until we see it again.

**Comment by rufuspollock** [comment]
INVALID. Closing this for now. This is a case where for some reason the push to s3 failed - we should handle errors better but not a big issue for now.
