### ISSUE TITLE
cli binary executable is very big 

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#138]
it is around 100 mb

cli delivery method needs to be improved

## Acceptance criteria

* [ ] binary is under ~50 mb

## Analysis

After cloning and running `npm install` the size of the repository is ~90 MB (while the size of the binary is 100 MB). analysing files and folders inside the biggest portion comes on `node_modules` (around 98%), meaning our dependencies are too many (hopefully) or  `package.json` includes ones that we are not using anymore  Eg: there still is `mocha` as dev dependency while we are using `ava` 

After cleaning package.json from unnecessary dependencies there are still some packages that we can remove: 
* `loadash` - think it is only used for `clone` and `deepclone` that we can do with `slice()` and/or `object.assign()` and get rid of whole library
* `mkdirp` maybe we can replace with fs, 
* `node-fetch` maybe we can fetch with Axios, or vice versa   ???
* `url-join` we can try and join URLs by ourselves
* more ???

**Removing extra packages did not help** - still 100mb, so we tried to remove dev-dependencies at all and pack only needed for production. `npm install --only=production` reduced size of `node_modules` from 90 to 50 mb on disck, but did not make any changes binary size is still ~100bm. will try webpack approach 

---

For using webpack we need one entry file that will include/import all the code that we need for CLI to work. Our current approach does not allow that scenario as we are requiring self-executable functions form `data.js` depending on what command is run from a user Eg: 

```
# input
data push

# behind the scenes  (in data.js)
require('data-push.js')
```

So as I said above webpack needs everything to be imported in entry file, that would be impossible as all the commands will be executed together on any command. Meaning we should either change the approach of executing commands or forget about webpack.

**Comment by justinclift** [comment]
This surprised me too when I saw it, and it did put me off a bit.  ~93MB or so.  Not even Golang binaries at that big, and they're statically linked. 😁

**Comment by anuveyatsu** [comment]
Still not fixed. We can open an issue with a question how to do it in https://github.com/zeit/pkg - will add it as todo into our todo list.

**Comment by anuveyatsu** [comment]
This issue was opened recently https://github.com/zeit/pkg/issues/214 - relates to us.

**Comment by zelima** [comment]
After cloning and running `npm install` the size of the repository is ~90 MB (while the size of the binary is 100 MB). analysing files and folders inside the biggest portion comes on `node_modules` (around 98%), meaning our dependencies are too many or (hopefully) `package.json` includes ones that we are not using anymore  Eg: there still is `mocha` as dev dependency while we are using `ava` (not sure if dev dependencies are also used when compiling binary).

@anuveyatsu will do PR and remove the ones that I think is extra and do review please

Also there are packages like 
* `loadash` - think it is only used for `clone` and `deepclone` that we can do with `slice()` and/or `object.assign()` and get rid of whole library
* `mkdirp` maybe we can replace with fs, 
* `node-fetch` maybe we can fetch with Axios, or vice versa   ???
* `url-join` we can try and join URLs by ourselves
* and more that I don't know what is used for...

**Comment by anuveyatsu** [comment]
@zelima re `node-fetch` we have decided to use it instead of `axios` so probably we should switch all code to avoid `axios` and then remove it.

Overall, I see two options here:

* try to uninstall all node modules and then install without dev-dependencies so when pkg builds it should not include dev-dependencies (this is just a guess): `npm install --only=production`
* to use webpack as it is done in `now-cli`, you can see that they doing `webpack && pkg dist/now.js -c package.json -o packed/now` - https://github.com/zeit/now-cli/blob/master/package.json#L14

**Comment by zelima** [comment]
see analysis section

**Comment by zelima** [comment]
WONTFIX. I suggest closing this as we have no clear understanding of how to fix it. at least unless we have more information about portions of the binary executable. related issue zeit/pkg#214
