### ISSUE TITLE
[push] QA review 8 Aug 2017

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#143]
* [FIXED] login with `data login --api https://api-testing.datahub.io` -> run `data push` -> says sucessfull but not live -> do same with --api flag it works: `data login --api https://api-testing.datahub.io` 
  * I expect that if I'm logged in once `with --api https://api-testing.datahub.io` I should not have to use that again and again on every push 
* [FIXED] `data push single_file.csv`:
	* `> Error! Cannot read property 'fields' of undefined`
* `data publish datapackage_with_tsv` says successful 
	* result http://testing.datahub.io/zelima/nasa-tsv
* [FIXED] After `push` command: I got url: `https://datahub.io/meiran1991@gmail.com/transform-example-gdp-uk`, it is not working, i need to add `next` into domain name.

**Comment by anuveyatsu** [comment]
FIXED. The only thing that is not fixed here is datapackage with `tsv` file. Checking http://testing.datahub.io/zelima/nasa-tsv/pipelines :
```
ValueError: Expected 9 fields in line 2, saw 7
```
which is probably due to data itself.
