### ISSUE TITLE
parse identifier supports datahub datasets

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#144]
parseIdentifier supports datahub datasets i.e. recognizes datahub.io in url and appropriately locates datapackage.json and creates the right kind of identifier structure.

## Acceptance criteria

* [x] I can parse any of:
  * [x] datahub url
  * [x] github url
  * [x] normal url to datapackage

## Tasks

https://github.com/datahq/data.js/issues/7

## Analysis

As we want to merge these changes into upstream repo `datapackage-identifier-js`, we should copy the code from there and refactor it - https://github.com/frictionlessdata/datapackage-identifier-js/blob/master/index.js (so we'll fix #68 as well): 

// on https://github.com/frictionlessdata/datapackage-identifier-js/blob/master/index.js#L77
```javascript
if (urlparts.host == 'datahub.io') {
  urlparts.host = 'pkgstore.datahub.io'
  ...
}
```

Also, need to refactor property names of the parsed object, see https://github.com/datahq/datahub-cli/issues/65

**Comment by rufuspollock** [comment]
I would merge this into data.js frankly.

Also does issue includes files as well as datasets.

Can you write out in detail a list of parse examples and resulting objects they generate.

**Comment by anuveyatsu** [comment]
@rufuspollock currently, we have following parser for dataset identifier (possibly, we do **not** need to touch files path parser here as it is irrelevant):

```javascript
const parseDatasetIdentifier = path_ => {
  return {
    path: path_,
    type: isUrl(path_) ? 'remote' : 'local'
  }
}
```

We want to have `parseDatasetIdentifier` function to handle datahub (and github) urls:

```javascript
const dhUrl = 'https://datahub.io/core/co2-ppm'
const identifier = parseDatasetIdentifier(dhUrl)
// identifier =
{
  path: 'https://pkgstore.datahub.io/core/co2-ppm/latest/',
  type: 'remote'
}

const ghUrl = 'https://github.com/datasets/co2-ppm'
const identifier2 = parseDatasetIdentifier(ghUrl)
// identifier2 =
{
  path: 'https://raw.githubusercontent.com/datasets/co2-ppm/master/',
  type: 'remote'
}
```

**Comment by rufuspollock** [comment]
@anuveyatsu how hard is it to extend this for paths? And what would be use case? I guess it would be getting a file on datahub or github ... - sounds minor to me for now! => we can leave .... (I encourage you to this kind of analysis).

Re analysis:

* Should we enhance our current identifier object (which is minimal) to be more like data-package-identifier. And what would this look like?
* Can we write out for local path, github, datahub, url what the input and output would look like (this is good analysis and makes writing tests very easy!)

**Comment by anuveyatsu** [comment]
@rufuspollock here are `input-output` scenarios for datahub, github, url and local path:

Notes:

* DataHub
  * `path` is for `extended` datapackage.json, but we need to access `logical` or original one somehow (probably need an API)
  * `resourcePath` is tricky if we use `original` datapackage.json (path wouldn't consider `data/csv|json` part)
* General
  * Not sure if we need `version` for now (should it be set to `latest` by default?)

```javascript
// datahub (e.g., https://datahub.io/core/co2-ppm)
{
  name: 'co2-ppm',
  owner: 'core',
  path: 'https://pkgstore.datahub.io/core/co2-ppm/latest', // but this path is for extended dp... how to get path for logical one?
  type: 'datahub',
  original: 'https://datahub.io/core/co2-ppm',
  version: 'latest', // (?)
  resourcePath: 'https://pkgstore.datahub.io/core/co2-ppm/latest/data/csv' // should we use pkgstore path here or may be we should use `./r/`
}

// github (e.g., https://github.com/datasets/co2-ppm)
{
  name: 'co2-ppm',
  owner: 'datasets',
  path: 'https://raw.githubusercontent.com/datasets/co2-ppm/master',
  type: 'github',
  original: 'https://github.com/datasets/co2-ppm'
  // version - not sure about that attribute
  resourcePath: 'https://raw.githubusercontent.com/datasets/co2-ppm/master'
}

// random url (e.g., https://example.com/path/to/dataset)
{
  name: 'dataset', // last parth of the path
  owner: null,
  path: 'https://example.com/path/to/dataset',
  type: 'url',
  original: 'https://example.com/path/to/dataset',
  version: ..., // (?)
  resourcePath: 'https://example.com/path/to/dataset/'
}

// local path (e.g., mydir/co2-ppm)
{
  name: 'co2-ppm', // last parth of the path
  owner: null,
  path: path.join(process.cwd(), 'mydir/co2-ppm'), // full path to the dir
  type: 'local',
  original: 'mydir/co2-ppm',
  version: ..., // (?)
  resourcePath: 'mydir/co2-ppm'
}
```

**Comment by anuveyatsu** [comment]
FIXED in the following issue https://github.com/datahq/data.js/issues/7
