### ISSUE TITLE
Split out data.js to dedicated lib

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#149]
Split out to https://github.com/datahq/data.js

And work out what we would need for data.js to run natively in node 8.

**Structure:**

* /lib
  * /index.js (with data.js and refactored identifier parser)
  * /parser
    * csv.js
    * xlsx.js
* /test
* package.json
* .gitignore
* .travis

**Comment by rufuspollock** [comment]
@anuveyatsu could you update on status here e.g.:

- How is data.js looking (what remains?)
- what changes remain in datahub-cli to use split out lib
- have you published to npm
- node 8 questions

**Comment by anuveyatsu** [comment]
@rufuspollock 
* it is identical to old one from `datahub-cli` (so we move out `/lib/utils/data.js` and `/lib/utils/parser/*` from datahub-cli)
* I think we just need to install `data.js` and refactor imports of `data.js` and nothing else is required - **[DONE]**
* http://npmjs.com/package/data.js
* it runs OK on either node 8 or 7.10 without Babel

**Comment by anuveyatsu** [comment]
FIXED, now we use `File` and `Dataset` classes from external npm library `data.js`.
