### ISSUE TITLE
Authentication on DataHub

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#15]
We want to authenticate users (publishers) prior pushing data packages (data files) into our server because DataHub's APIs that we're going to use (upload, purge, etc.) require authentication. To prove an identity, it needs to get temporal JWT token by providing secret key (issued after a user signs up on DataHub). More information can be found here http://docs.datapackaged.com/developers/authentication/

## Acceptance criteria

* [x] function for authentication of a publisher

## Tasks

TODO

## Analysis

To obtain a temporal JWT token, client should send POST request to /api/auth/token. Request should have json-encoded body with 'username' and 'secret' keys, where 'secret' is an API-KEY (token / secret key) of the user:

```javascript
axios.post(
  'https://datapackaged.com/api/auth/token',
  {
    'username': 'my_username',
    'secret': '1dd5f984bc'
  }
).then(response => {
  console.log(response)
}).catch(error => {
  console.log(error)
})
```

If the username and API-KEY are valid, server will return json response with JWT token: `{'token': 'a6d8b887'}`:

```javascript
const auth_token = response.data['token']
```

This token should be temporarily stored by the client. To access any API method with authentication, client should include this token in the "Authorization" header.

Code below is a pseudo code:
```javascript
axios.post(api_url, {'Authorization', 'Bearer %s' % auth_token})
```

**Comment by zelima** [comment]
FIXED
