### ISSUE TITLE
Auto copy to clipboard the published data package link

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#156]
As a Publisher I want the url at the end of push auto-copied to my clipboard so that I save time and don't make errors (in copying)

## Acceptance criteria

* [x] url is copied to clipboard

## Tasks

* [x] Analyse
* [ ] ~~Implement (is it worth a test??)~~

## Analysis

Use https://github.com/sindresorhus/clipboardy

```
const { write: copyToClipboard } = require('clipboardy')

...

await copyToClipboard(url)

... mention that url is copied to clipboard in output e.g.
Here's your url: .... (copied to clipboard)
``` #

**Comment by anuveyatsu** [comment]
FIXED, url is auto copied to clipboard and output is:
```
🙌  your data is published!
🔗  https://datahub.io/anuveyatsu/co2-ppm (copied to clipboard)
```
