### ISSUE TITLE
[push] cannot push pdf files

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#167]
If I try to push `data push myfile.pdf`, it would give me the following error:

```
> Error! File is not in known tabular format.
```

## Acceptance criteria

* [x] I can push pdf files

## Tasks

* [x] push PDF files as non-tabular resources

**Comment by rufuspollock** [comment]
@anuveyatsu please close if this is fixed.

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datahq/datahub-cli/commit/3d98305a6a2ba3520de1c3fc06dfb363a4b3d265

**Comment by rufuspollock** [comment]
@anuveyatsu it would be nice if you also linked an example test file you pushed to testing.
