### ISSUE TITLE
Do metadata validation prior to pushing

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#205]
We need to validate datapackage.json prior pushing due to following reasons:

* users don't push invalid metadata. Allowing them to push metadata with schedule, e.g., 10m would lead to pipelines re-run every 10m with exactly same result.
* we can provide good error message to users so they fix their metadata and then push

## Acceptance criteria

* [x] `data push` validates metadata prior to pushing dataset

## Tasks

* [x] refactor `data-push.js` to validate metadata

## Analysis

use `validateMetadata` method from `datahub-client`, since `validate` function validates both metadata and data. In our case we use a validation report on front-end side from goodtables ui, so only validating metadata is enough.

**Comment by Mikanebu** [comment]
FIXED, we validate metadata prior to pushing
