### ISSUE TITLE
Refactor code to be Object Oriented 

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#21]
Refactor code to export one Client class with bunch of method on it instead of exporting number of different functions from `/lib/index.js`. (See analysis)

## Acceptance Criteria

- [ ] we are using classes  instead of exporting separate functions 

## Tasks

- [ ] refactor tests
- [ ] refactor code

## Analysis 

currently we are exporting functions from `lib/index.js` and using them in `bin/datahub.js` as follows:

```
// lib/index.js
exports.get = function(publisher, ...) {
 // all the logic
 return data
}

// bin/datahub.js

let client = require('../lib/inidex.js')

let data = client.get(publisher, ...)
```

Currently there are few functions in `lib/index.js`, but as the codbase will grow, different methods will have things in common Eg: cinfig. I propose to refactor `lib/index.js` to export class Client that will have constructor and all the needed methods on it like `get`, `push`, `purge` etc... Code above would look like:

```
// lib/index.js
exports.Client = class  {
 constructor (config ) {
   this.config = config 
 }
 
get() {...} 
push() {...}
etc...
}

// bin/datahub.js

const Client = require('../lib/inidex.js')
let client = new Client(config)

let data = client.get(publisher, ...)
```

**Comment by anuveyatsu** [comment]
CLOSING for now as we have decided to use approach from https://github.com/zeit/now-cli
