### ISSUE TITLE
When csv file name is not valid according to the spec, we have to handle it prior to publishing

### ISSUE THREAD

**Issue by Mikanebu** [datopian/data-cli#219]
When pushing single csv file, it should lowercase it according to the specifications

## Acceptance criteria

* [x] we're lowercasing the name of the resource

## Tasks
* [x] analysis
* [x] refactor datahub-cli to check file name if invalid, handle it prior to publishing

## Analysis
Please, see https://datahub.io/Mikanebu/test-polite-pig-2/pipelines
Original resourse is `ville_vitry_Subventions_2017_comma_csv.csv`

There are two solutions to solve this issue

* We can handle it in our side
  * We have to refactor `data.js` - it gets file size
  * We have to refactor `datahub-client` 
* We can validate it prior to pushing and throw error
```
> Error! File name must match following pattern: /^([-a-z0-9._\/])+$/
```

There are cases when user wants to publish file with different language name. For example, `популяция.csv`. In this case, pipeline fails when adding resource 
```
ERROR :Data Package validation error: Descriptor validation error: 'популяция_csv' does not match '^([-a-z0-9._/])+$' at "name" in descriptor and at "properties/name/pattern" in profile
```

The optimal solution would be to validate and throw error message:
```
> Error! File name must match following pattern: /^([-a-z0-9._\/])+$/
```

**Comment by rufuspollock** [comment]
@Mikanebu i think there are two parts here: the original issue about lowercasing and more complex question of non-ascii file names. Can we focus on lowercase for now and open a separate issue about non-ascii.

**Comment by Mikanebu** [comment]
created issue about non-ascii https://github.com/datahq/datahub-cli/issues/235

**Comment by Mikanebu** [comment]
FIXED, now we lowercase file name prior to publishing
