### ISSUE TITLE
data validate throws unexpected error 

### ISSUE THREAD

**Issue by Mikanebu** [datopian/data-cli#223]
We want to update `data  package` schema path, so our `data validate` works fine. 

## Acceptance criteria

* [x] `data validate` works fine

## Tasks

* [x] update `data package` schame path in `validate.js` in `datahub-client` repo. 

## Analysis
Instead of showing error messages, `data validate` gives the following error
```
Error! Profiles registry hasn't profile data-package
```
The proper error message should be 
```
> Error! Error: Descriptor validation error:
          Missing required property: title
          at "/sources/0" in descriptor and
          at "/properties/sources/items/required/0" in profile,Error: Descriptor validation error:
          Missing required property: title
          at "/sources/1" in descriptor and
          at "/properties/sources/items/required/0" in profile,Error: Descriptor validation error:
          Missing required property: title
          at "/contributors/0" in descriptor and
          at "/properties/contributors/items/required/0" in profile
```
This happened after releasing new CLI v0.6.2.

After splitting datahub-client from datahub-cli repo, we encountered a new error in `data validate` where it cannot find `data package` schema. So we need to update by providing url for schema, not local path.

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datahq/datahub-client/pull/2 - new release 0.6.3 should be issued by @Mikanebu
