### ISSUE TITLE
[validate] with non-tabular data results in error (with unhelpful message)

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#243]
Running `data validate` on a data package with non tabular data results in:

```
> Error! Cannot read property 'replace' of undefined
```

I suspect this is because the result is not true but false but the errors array looks like:

```
[{},{}]
```

We need to skip validation when a resource is not a tabular data resource.

## Tasks

* [ ] confirm source of bug
* [ ] rework validation to skip data validation if non-tabular data resource

**Comment by anuveyatsu** [comment]
DUPLICATE - this was already fixed in the other issues - now we validate resources with format `csv` or `tsv` only.
