### ISSUE TITLE
[bug] `data get` does not work inside a NTFS folder

### ISSUE THREAD

**Issue by AcckiyGerman** [datopian/data-cli#246]
## Acceptance criteria

* [x] dataset could be downloaded inside a NTFS folder on Ubuntu linux

## Tasks

* [x] debug the error
* [ ] write test
* [x] fix method

## Analysis

Program version: https://github.com/datahq/data-cli/releases/download/v0.6.3/data-linux
OS version: Ubuntu 16.04
```shell
# usual ext4 folder
user@pc:~$ data get http://datahub.io/core/co2-ppm
Time elapsed: 1.33 s
Dataset/file is saved in "co2-ppm."

# NTFS folder
user@pc:~$ cd Downloads
user@pc:~/Downloads$ data get http://datahub.io/core/co2-ppm
⠹ Loading...> Error! EINVAL: invalid argument, open 'co2-ppm.'
⠇ Loading...^C
```

@anuveyatsu 
>On macOS following happens:
>It successfully finishes "getting" the dataset but it actually downloads page content in HTML.

@acckiygerman 
that is another bug: https://github.com/datahq/datahub-qa/issues/43

**Comment by zelima** [comment]
@AcckiyGerman @anuveyatsu Think this belongs to https://github.com/datahq/datahub-client repo

**Comment by anuveyatsu** [comment]
@zelima yes, but it can stay here as was faced during CLI usage

**Comment by AcckiyGerman** [comment]
FIXED:   Duplicate of https://github.com/datahq/datahub-qa/issues/55
