### ISSUE TITLE
Can not login when data-linux not in /usr/bin direcory

### ISSUE THREAD

**Issue by alex-bender** [datopian/data-cli#248]
When I'm trying to login with the `data-linux` binary from `Downloads` folder I'm getting this error:
```
$ ~/Downloads/data-linux login
? Login with... Github
> Opening browser and waiting for you to authenticate online
> Error! spawn /home/alex/Downloads/xdg-open ENOENT
```

Everything works fine if `data-linux` is in `/usr/bin/` directory. (and in any of PATH folders, I suppose).

At the first glance it seems to be that broken `xdg-open` discover method was implemented.

OS: Debian 8

**Comment by Mikanebu** [comment]
@alex-bender Thanks for reporting this. Could take a look on our [documentation](http://datahub.io/docs/getting-started/installing-data#installing-binaries), we included a note for `linux` users?

**Comment by alex-bender** [comment]
Oh, that's already documented.. Sorry.
But still it seems little bit strange that `xdg-open` are invoked by abs path, (as I suppose).
But also I believe that there was some reason for that.
Anyway, thanks for response!

**Comment by Mikanebu** [comment]
@alex-bender You are welcome! Also, any questions regarding DataHub, please join our gitter channel on https://gitter.im/datahubio/chat
