### ISSUE TITLE
`data get <file-on-the-github>` downloads a html page

### ISSUE THREAD

**Issue by AcckiyGerman** [datopian/data-cli#250]
As a user, I want to get some file using link from the github, so I could use it locally.

## Acceptance criteria
* [x] ` data get  https://github.com/frictionlessdata/test-data/blob/master/files/csv/separators/comma.csv
` downloads csv file, not the html

## Tasks
* [ ] write test
* [x] add `?raw=true` to the links, that point on the files, that are placed on github domain

## Analysis
When the user is trying to paste some link from the github, like
`data get https://github.com/datasets/finance-vix/blob/master/data/vix-daily.csv`
  99% that he wants the csv, not html, even if the github will return html from this link.

I know that user can use `https://raw.githubusercontent.com` or add `?raw=true` manually, but why not to help him?

**Comment by AcckiyGerman** [comment]
@zelima could you comment this issue and close if we WONTFIX it.
We already fixed
 `data get http://github.com/datasets/<dataset>`
And I think it is easy to implement
 `data get http://github.com/datasets/<dataset>/<datafile>`

**Comment by AcckiyGerman** [comment]
ah, sorry, now I see this issue https://github.com/datahq/datahub-qa/issues/56

**Comment by Mikanebu** [comment]
FIXED, now, we can use data get for any file in GitHub
