### ISSUE TITLE
No details in release

### ISSUE THREAD

**Issue by Stephen-Gates** [datopian/data-cli#251]
After the software updates, I get a notification message, "Click to find out what's changed" however there is often no information on the releases page https://github.com/datahq/data-cli/releases

Please add this information as a standard practice so I know what bugs are fixed or new features are available.

**Comment by anuveyatsu** [comment]
@Stephen-Gates I agree this is important to have a changelog or something similar to give users understanding of what's happening. You can see we've included it in the v0.6.5 and I've added small tag message for v0.6.7, which is I believe isn't noticeable.

I have added more descriptive change message now - https://github.com/datahq/data-cli/releases/tag/v0.6.7
