### ISSUE TITLE
When pushing empty Excel file CLI tool stops responding

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#260]
Prepared Excel file with a sheet with 0 rows and pushed it, so CLI stuck while pushing. Spinner stopped and I'm not able to terminate the process.

Sample data file: https://github.com/frictionlessdata/test-data/blob/master/data-files/empty-files/empty.xls

## Acceptance criteria

* [x] Either don't allow to push on CLI with clear message or give error message on the showcase page

## Tasks

* [x] investigate/analyse the source of the issue and create further tasks accordingly

**Comment by AcckiyGerman** [comment]
FIXED.
trying to push an empty excel file , the program will reply with `> Error! You cannot push an empty sheet. Please, add some data and try again.`
