### ISSUE TITLE
Pushing something that is not Excel but has .xls(x) extension

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#261]
When pushing a file with Excel extension but actually not Excel, I'm getting confusing error message on showcase page: "File is not a zip file"

Steps to reproduce:

* take a XLS file, change its extension to .xlsx and push
* take a CSV file, change its extension to .xlsx and push
* take a PDF file, change its extension to .xlsx and push

## Acceptance criteria

* [ ] processing dataset fails with clear message saying that provided file has unexpected content

## Tasks

* [ ] analyse how we can improve error message and create further tasks accordingly

**Comment by AcckiyGerman** [comment]
`data push fake.xlsx` which was an xls in original.
Showcase page:
```
File "/usr/local/lib/python3.6/zipfile.py", line 1108, in __init__
self._RealGetContents()
File "/usr/local/lib/python3.6/zipfile.py", line 1175, in _RealGetContents
raise BadZipFile("File is not a zip file")
```

**Comment by anuveyatsu** [comment]
WONTFIX - https://github.com/datahq/datahub-qa/issues/57
