### ISSUE TITLE
[push] no warning for Invalid URI

### ISSUE THREAD

**Issue by AcckiyGerman** [datopian/data-cli#286]
When `pathType` set to 'remote', `data push` does not check if the `path` is valid URI, and this dataset will be pushed.
```json
"resources": [
    {
      "path": "no-such-file.csv",
      "pathType": "remote",
```

Then we got an error on the dataset page:
```
raise exceptions.HTTPError(str(exception))

tabulator.exceptions.HTTPError: 404 Client Error: Not Found for url: https://s3.amazonaws.com/rawstore-testing.datahub.io/no-such-file.csv
```

## Acceptance criteria

* [ ] User have a warning, when `remote` path is not actually remote.

**Comment by anuveyatsu** [comment]
WONTFIX - I think publishers should be responsible for providing correct `pathType` property. Notice that auto-generated descriptors would have correct `pathType`s.
