### ISSUE TITLE
Using "test" publisher automate QA tests for "push" that require publishing into datahub

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#291]
## Acceptance criteria

* [x] all or majority of QA tests for "push" command are automated

## Tasks

* [x] go through the QA tests list and identify which ones can/should be automated here
* [x] implement automation

**Comment by zelima** [comment]
@anuveyatsu is there something remaining here? I see the related PR is merged

**Comment by anuveyatsu** [comment]
FIXED - all "push" related tests are in `/test/push/` directory and runs only on tagged commits in the `before_deploy` script.
