### ISSUE TITLE
No example or documentation for pushing with --name flag

### ISSUE THREAD

**Issue by Branko-Dj** [datopian/data-cli#344]
There is no documentation and nothing in README or in `docs/` about pushing with --name flag. When runnning `data push -h` no example is given for this either

## Tasks
* Add an example in README and docs/ with an example for `data push --name=test`
* Add the same example in the output of `data push -h` command

**Comment by zelima** [comment]
FIXED here https://github.com/datahq/data-cli/commit/dd0db0e8d10d9130735354740625419de66c7556 (typo in ref)
