### ISSUE TITLE
non-interactive mode (?)

### ISSUE THREAD

**Issue by ivotron** [datopian/data-cli#345]
Is there a way of using the CLI tool in non-interactive mode (I'd like to use it in some automated scripts)?

**Comment by anuveyatsu** [comment]
Hi @ivotron the CLI uses https://github.com/datahq/datahub-client library to interact with the datahub services. You can read this blog post for more information:

https://datahub.io/blog/javascript-sdk-for-data-deployment

**Comment by zelima** [comment]
@ivotron @anuveyatsu Would you mind closing this issue?

**Comment by ivotron** [comment]
@zelima @anuveyatsu, can be closed IMO. Based on the links you shared (guides on how to programatically use the API), the answer to "can the CLI tool be used in non-interactive mode" is **no**, right?

**Comment by anuveyatsu** [comment]
@ivotron in my understanding a CLI tool supposed to be interactive but you can use its dependencies if you want to automate something. The answer is probably "no, it cannot be non-interactive, but you can use the upstream library in your script".
