### ISSUE TITLE
CLI asks to update 0.9.5 -> 0.10.1, but this version doesn't have a binary

### ISSUE THREAD

**Issue by vitorbaptista** [datopian/data-cli#364]
Any time I run `data`, it complains:

```
▶ data validate


   ╭──────────────────────────────────────╮
   │                                      │
   │   Update available 0.9.5 → 0.10.1    │
   │   Run npm i -g data-cli to update    │
   │                                      │
   ╰──────────────────────────────────────╯

If you've installed data tool using our executable binary then follow instructions below:

wget https://github.com/datahq/data-cli/releases/download/v0.10.1/data-linux.gz
gunzip -f data-linux.gz && chmod +x data-linux && sudo mv data-linux /usr/local/bin/data
data -v # should print 0.10.1
```

However, the `data-linux.gz` file doesn't exist on v0.10.1, so `wget https://github.com/datahq/data-cli/releases/download/v0.10.1/data-linux.gz` returns a 404.

**Comment by rufuspollock** [comment]
WONTFIX.

@vitorbaptista thanks for reporting and i have the same issue even after doing `npm i -g data-cli` so i suspect there is a bug here in that it thinks there is a newer version when there isn't.

As this tool has been dormant for a little while I don't think this will be top priority - as we're about to pick it back up in various ways and i suspect this will get fixed along the way.
