### ISSUE TITLE
Misc improvements from 15 June 2017 meeting

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#64]
* error message is not clear (e.g. when I do `data purge` and there is no datapackage.json)
* there is typo in error message mentioned previously
* [x] spinner should not appear when there are no external calls
* [wf] data commands need a little introduction (explanation)
  * remove h1 headings and have intro paragraph instead
* [x] `data help` remove table - have simple list of commands
  * Reorder list of commands in help according to the importance of usage.(get, push, info etc)

**Comment by rufuspollock** [comment]
FIXED or INVALID (e.g. obsolete - e.g. purge is not there for now).
