### ISSUE TITLE
New approach for configurations

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#95]
At the moment, we require users to setup their configs using `data config` command. We want to eliminate this step by having default configs (see https://github.com/datahq/frontend/tree/master/config).

Once user logins we create `~/.datahub.json` file with following properties:

```
{
  token: <token>,
  email: <email>,
  username: <username> // if n/a then use hash of email
}
```

## Acceptance criteria

* [ ] As a user I don't need to setup configs to work with CLI

## Tasks

* [ ]

**Comment by rufuspollock** [comment]
FIXED. This was done a few days ago.
